name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.0.0
  http: ^0.13.0  # required by web3dart for JSON-RPC requests
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  timeago: ^3.7.0
  shimmer: ^3.0.0
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  supabase_flutter: ^2.8.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^4.2.1
  lottie: ^3.0.0
  walletconnect_dart: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
