// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTLRe_dD-4BXdzl25kSzv9WeIhQhrLzQ',
    appId: '1:447279222567:web:10c249a057a0f8e59b2302',
    messagingSenderId: '447279222567',
    projectId: 'poetloom',
    authDomain: 'poetloom.firebaseapp.com',
    storageBucket: 'poetloom.firebasestorage.app',
    measurementId: 'G-6YZEGZ09DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlrkJUKKR2SkjRptFcViwtR9nqJDQ3nCE',
    appId: '1:447279222567:android:979fbe9eb6022c0d9b2302',
    messagingSenderId: '447279222567',
    projectId: 'poetloom',
    storageBucket: 'poetloom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOoUIyG1cRSZbaBb0yod6qqrt4VVKwHQ',
    appId: '1:447279222567:ios:0e3aebdce84f82fd9b2302',
    messagingSenderId: '447279222567',
    projectId: 'poetloom',
    storageBucket: 'poetloom.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQOoUIyG1cRSZbaBb0yod6qqrt4VVKwHQ',
    appId: '1:447279222567:ios:0e3aebdce84f82fd9b2302',
    messagingSenderId: '447279222567',
    projectId: 'poetloom',
    storageBucket: 'poetloom.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYTLRe_dD-4BXdzl25kSzv9WeIhQhrLzQ',
    appId: '1:447279222567:web:f9198878c8c477fb9b2302',
    messagingSenderId: '447279222567',
    projectId: 'poetloom',
    authDomain: 'poetloom.firebaseapp.com',
    storageBucket: 'poetloom.firebasestorage.app',
    measurementId: 'G-14J2RV0PF4',
  );
}
